# Generated by Django 2.1.2 on 2019-04-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='None', max_length=265)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('kosher', models.BooleanField(default=False)),
                ('halal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=265)),
                ('email', models.EmailField(max_length=265)),
                ('food_available', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=265)),
                ('location', models.CharField(blank=True, max_length=265)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
