# Generated by Django 2.1.2 on 2019-03-21 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=265)),
                ('amount_gold', models.IntegerField(blank=True, null=True)),
                ('food_available', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=265)),
                ('location', models.CharField(blank=True, max_length=265)),
            ],
        ),
    ]
