# Generated by Django 2.1.2 on 2019-04-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='food_available',
        ),
        migrations.AddField(
            model_name='food',
            name='food_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='location',
            field=models.CharField(max_length=265),
        ),
    ]
