# Generated by Django 2.1.2 on 2019-04-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190425_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_available',
            new_name='available',
        ),
    ]
