# Generated by Django 2.1.2 on 2019-04-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190425_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
