# Generated by Django 2.1.2 on 2019-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20190426_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='lat',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='lng',
            field=models.FloatField(max_length=6, null=True),
        ),
    ]
