# Generated by Django 2.1.2 on 2019-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20190426_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
