# Generated by Django 2.1.2 on 2019-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20190426_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
