# Generated by Django 2.1.2 on 2019-04-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_food_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(),
        ),
    ]
